variable "name" {}
variable "location" {}
variable "resource_group_name" {}
variable "sku_name" {}
variable "sku_tier" {}
variable "min_capacity" {}
variable "max_capacity" {}
variable "gateway_ip_configuration_name" {}
variable "subnet_id" {}
variable "frontend_port_name" {}
variable "frontend_port" {}
variable "frontend_ip_configuration_name" {}
variable "public_ip_address_id" {}
variable "backend_address_pool_name" {}
variable "backend_http_settings_name" {}
variable "backend_http_settings_port" {}
variable "request_timeout" {}
variable "http_listener_name" {}
variable "request_routing_rule_name" {}
variable "priority" {}
